name: 'Terraform'
 
on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:
 
jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

    runs-on: ubuntu-latest
    environment: production
 
    defaults:
      run:
        shell: bash
 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | bash
      
    - name: AZ CLI Version Check
      run: az --version
         
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.4.6
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: "./terraform"
 
    #- name: 'Terraform Format'
      #uses: hashicorp/terraform-github-actions@master
      #with:
        #tf_actions_version: 1.4.6
        #tf_actions_subcommand: 'fmt'
        #tf_actions_working_dir: "./terraform"
    
    - name: 'Terraform Validate'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.4.6
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: "./terraform"
         
    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.4.6
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: "./terraform"
 
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.4.6
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: "./terraform"

    #- name: Terraform Destroy
    #  uses: hashicorp/terraform-github-actions@master
    #  with:
    #    tf_actions_version: 1.4.6
    #    tf_actions_subcommand: 'destroy'
    #    tf_actions_working_dir: "./terraform"